# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Setup MySQL
      # You may pin to the exact commit or the version.
      # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
      uses: mirromutth/mysql-action@v1.1
      with:
        # --character-set-server - The character set of MySQL server
        character set server: utf8mb4 # optional, default is utf8mb4
        # --collation-server - The character collation of MySQL server
        collation server: utf8mb4_unicode_ci # optional, default is utf8mb4_general_ci
        # MYSQL_ROOT_PASSWORD - root superuser password
        mysql root password: root # optional, default is 
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: urlshortener_test # optional, default is 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run migrate:postgres:ci
    - run: npm run test:ci
